In [2]:
#AIDI Project V2
#The purpose of this notebook is to implement the proposed method in the SOW2 to generate realistic greenhouse temperatures 
#based on various weather conditions recorded in Windsor Ontario.
#The Data will need to be cleaned and some features need to be prepared to be implemented with the proposed method 
#They are: Outside Temp, Wind Dir, Wind Speed, Wind Gust, and Condition.
#Some of these features will be returned to their original states once they have been used to generate the Inside Temp feature
#They are: Wind Dir and Condition
#Once the we have the generated data points for Inside Temp they will be shifted forward one hour so each row has a refrence to
#the Inside Temp 1 Hour prior. This will be useful when implementing a model since it will be able to uncover a relationship
#between future weather features and a supplied current greenhouse temperature to predict a future greenhouse temperature.

import pandas as pd
import numpy as np

def fahr_to_celsius(temp_fahr):
    """Convert Fahrenheit to Celsius
    
    Return Celsius conversion of input"""
    temp_celsius = (temp_fahr - 32) * 5 / 9
    return round(temp_celsius, 2)

weatherData = pd.read_csv("WeatherData.csv")

In [3]:
display(weatherData)

,Date,Time,Outside Temp,Dew Point,Humidity,Wind Dir,Wind Speed,Wind Gust,Pressure,Precip,Condition,Unnamed: 11
0,2019-07-01,0:00,63 F,59 F,88 %,NE,5 mph,0 mph,29.37 in,0.0 in,Fair,NaN
1,2019-07-01,1:00,63 F,59 F,88 %,ENE,3 mph,0 mph,29.36 in,0.0 in,Fair,NaN
2,2019-07-01,2:00,63 F,59 F,88 %,S,2 mph,0 mph,29.34 in,0.0 in,Fair,NaN
3,2019-07-01,3:00,63 F,59 F,88 %,SSW,3 mph,0 mph,29.34 in,0.0 in,Fair,NaN
4,2019-07-01,4:00,61 F,57 F,88 %,CALM,0 mph,0 mph,29.34 in,0.0 in,Fair,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2113,2019-08-31,19:00,64 F,57 F,77 %,E,5 mph,0 mph,29.60 in,0.0 in,Cloudy,NaN
2114,2019-08-31,20:00,63 F,57 F,82 %,E,5 mph,0 mph,29.60 in,0.0 in,Cloudy,NaN
2115,2019-08-31,21:00,63 F,54 F,72 %,ENE,10 mph,0 mph,29.60 in,0.0 in,Fair,NaN
2116,2019-08-31,22:00,63 F,54 F,72 %,ENE,8 mph,0 mph,29.60 in,0.0 in,Mostly Cloudy,NaN
2117,2019-08-31,23:00,63 F,54 F,72 %,E,6 mph,0 mph,29.60 in,0.0 in,Cloudy,NaN

In [4]:
#First lets drop the features we will not be using, Wind Gust may be a value we can return to look at if we later want to add 
#more features to the model however the others are not typically forcasted on weather sites so we will not be using them.
#During research they also did not come up as points of influence on internal greenhouse temperature

weatherData = weatherData.drop(['Dew Point', 'Wind Gust', 'Pressure', 'Precip', 'Unnamed: 11'], axis=1)
display(weatherData)

,Date,Time,Outside Temp,Humidity,Wind Dir,Wind Speed,Condition
0,2019-07-01,0:00,63 F,88 %,NE,5 mph,Fair
1,2019-07-01,1:00,63 F,88 %,ENE,3 mph,Fair
2,2019-07-01,2:00,63 F,88 %,S,2 mph,Fair
3,2019-07-01,3:00,63 F,88 %,SSW,3 mph,Fair
4,2019-07-01,4:00,61 F,88 %,CALM,0 mph,Fair
...,...,...,...,...,...,...,...
2113,2019-08-31,19:00,64 F,77 %,E,5 mph,Cloudy
2114,2019-08-31,20:00,63 F,82 %,E,5 mph,Cloudy
2115,2019-08-31,21:00,63 F,72 %,ENE,10 mph,Fair
2116,2019-08-31,22:00,63 F,72 %,ENE,8 mph,Mostly Cloudy
2117,2019-08-31,23:00,63 F,72 %,E,6 mph,Cloudy

In [5]:
#Now we can start preparing the data to be used in the method which will generate greenhouse temperatures, most of the features 
#need to be converted from strings to floats/ints

weatherData['Outside Temp'] = weatherData['Outside Temp'].map(lambda x: x.replace("F", ""))
weatherData['Outside Temp'] = weatherData['Outside Temp'].map(lambda x: x.strip())
weatherData['Humidity'] = weatherData['Humidity'].map(lambda x: x.replace("%", ""))
weatherData['Humidity'] = weatherData['Humidity'].map(lambda x: x.strip())
weatherData['Humidity'] = weatherData['Humidity'].astype(int)
weatherData['Wind Speed'] = weatherData['Wind Speed'].map(lambda x: x.replace("mph", ""))
weatherData['Wind Speed'] = weatherData['Wind Speed'].map(lambda x: x.strip())
weatherData['Wind Speed'] = weatherData['Wind Speed'].astype(int)
display(weatherData)

,Date,Time,Outside Temp,Humidity,Wind Dir,Wind Speed,Condition
0,2019-07-01,0:00,63,88,NE,5,Fair
1,2019-07-01,1:00,63,88,ENE,3,Fair
2,2019-07-01,2:00,63,88,S,2,Fair
3,2019-07-01,3:00,63,88,SSW,3,Fair
4,2019-07-01,4:00,61,88,CALM,0,Fair
...,...,...,...,...,...,...,...
2113,2019-08-31,19:00,64,77,E,5,Cloudy
2114,2019-08-31,20:00,63,82,E,5,Cloudy
2115,2019-08-31,21:00,63,72,ENE,10,Fair
2116,2019-08-31,22:00,63,72,ENE,8,Mostly Cloudy
2117,2019-08-31,23:00,63,72,E,6,Cloudy

In [6]:
#Converting the temperatures to Celsius

weatherData['Outside Temp'] = fahr_to_celsius(pd.to_numeric(weatherData['Outside Temp']))
display(weatherData)

,Date,Time,Outside Temp,Humidity,Wind Dir,Wind Speed,Condition
0,2019-07-01,0:00,17.22,88,NE,5,Fair
1,2019-07-01,1:00,17.22,88,ENE,3,Fair
2,2019-07-01,2:00,17.22,88,S,2,Fair
3,2019-07-01,3:00,17.22,88,SSW,3,Fair
4,2019-07-01,4:00,16.11,88,CALM,0,Fair
...,...,...,...,...,...,...,...
2113,2019-08-31,19:00,17.78,77,E,5,Cloudy
2114,2019-08-31,20:00,17.22,82,E,5,Cloudy
2115,2019-08-31,21:00,17.22,72,ENE,10,Fair
2116,2019-08-31,22:00,17.22,72,ENE,8,Mostly Cloudy
2117,2019-08-31,23:00,17.22,72,E,6,Cloudy

In [7]:
#There are days where many additional recordings were made but since we are doing hourly predictions lets remove them for now, 
#again we can come back and return these values later if the model requires more data.

i = 0
for x in weatherData['Time']:
    if ':00' in x:
        i = i+1
    else:
        weatherData = weatherData.drop(i, axis=0)
        i = i+1

In [8]:
weatherData['Time'].unique()

array(['0:00', '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00',
       '8:00', '9:00', '10:00', '11:00', '12:00', '13:00', '14:00',
       '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00',
       '22:00', '23:00'], dtype=object)

In [9]:
display(weatherData)

,Date,Time,Outside Temp,Humidity,Wind Dir,Wind Speed,Condition
0,2019-07-01,0:00,17.22,88,NE,5,Fair
1,2019-07-01,1:00,17.22,88,ENE,3,Fair
2,2019-07-01,2:00,17.22,88,S,2,Fair
3,2019-07-01,3:00,17.22,88,SSW,3,Fair
4,2019-07-01,4:00,16.11,88,CALM,0,Fair
...,...,...,...,...,...,...,...
2113,2019-08-31,19:00,17.78,77,E,5,Cloudy
2114,2019-08-31,20:00,17.22,82,E,5,Cloudy
2115,2019-08-31,21:00,17.22,72,ENE,10,Fair
2116,2019-08-31,22:00,17.22,72,ENE,8,Mostly Cloudy
2117,2019-08-31,23:00,17.22,72,E,6,Cloudy

In [10]:
weatherData["Wind Dir"].unique()

array(['NE', 'ENE', 'S', 'SSW', 'CALM', 'VAR', 'SSE', 'SW', 'WSW', 'W',
       'WNW', 'NW', 'NNW', 'NNE', 'SE', 'N', 'E', 'ESE', nan],
      dtype=object)

In [11]:
#1 row with missing value for wind direction, wind speed was 0 at the time so lets put CALM into this missing value

weatherData["Wind Dir"].isna().sum()

1

In [12]:
weatherData.loc[weatherData['Wind Dir'].isna()]

,Date,Time,Outside Temp,Humidity,Wind Dir,Wind Speed,Condition
413,2019-07-15,11:00,28.89,40,NaN,0,Mostly Cloudy

In [13]:
weatherData.loc[weatherData['Wind Dir'].isna(), 'Wind Dir'] = 'CALM'

In [14]:
weatherData["Wind Dir"].isna().sum()

0

In [15]:
weatherData['Wind Speed'].unique()

array([ 5,  3,  2,  0,  6,  7, 10,  9,  8, 13, 12, 14, 15, 16, 17, 18, 20,
       21, 22, 23, 26])

In [16]:
weatherData['Condition'].unique()

array(['Fair', 'Mostly Cloudy', 'Partly Cloudy', 'Cloudy', 'Light Rain',
       'Thunder in the Vicinity', 'Light Rain with Thunder', 'Mist',
       'Mostly Cloudy / Windy', 'Fair / Windy', 'T-Storm', 'Thunder',
       'Partly Cloudy / Windy', 'Haze', 'Heavy T-Storm', 'Cloudy / Windy'],
      dtype=object)

In [17]:
#No missing values for wind speed or condition
#Changing time to an integer temporarilly

weatherData['Time'] = weatherData['Time'].map(lambda x: x.replace(":00", ""))

#For the predictions we want datapoints during hours of sunlight which are from 6AM to 9PM in the July - August months.
#Remove rows where the time is outside this range.

for index, row in weatherData.iterrows():
        weatherData.loc[index, 'Time'] = int(row['Time'])    

weatherData.drop(weatherData[weatherData.Time < 6].index, inplace=True)
weatherData.drop(weatherData[weatherData.Time > 21].index, inplace=True)

display(weatherData)

,Date,Time,Outside Temp,Humidity,Wind Dir,Wind Speed,Condition
6,2019-07-01,6,17.22,88,ENE,3,Mostly Cloudy
7,2019-07-01,7,20.00,78,SSE,6,Fair
8,2019-07-01,8,23.89,69,SSW,7,Fair
9,2019-07-01,9,26.11,54,SW,10,Partly Cloudy
10,2019-07-01,10,26.11,54,SW,9,Partly Cloudy
...,...,...,...,...,...,...,...
2111,2019-08-31,17,20.00,52,E,7,Cloudy
2112,2019-08-31,18,18.89,68,E,6,Cloudy
2113,2019-08-31,19,17.78,77,E,5,Cloudy
2114,2019-08-31,20,17.22,82,E,5,Cloudy
2115,2019-08-31,21,17.22,72,ENE,10,Fair

In [18]:
#Now lets make a copy before we convert the Wind Dir feature and Condition feature to numeric values.
#For more information on how this conversion works check the SOW2.

weatherData0 = weatherData.copy()

for index, row in weatherData.iterrows():
    if row['Condition'] == 'Fair' or row['Condition'] == 'Fair / Windy':
        weatherData.loc[index, 'Condition'] = 1
    elif row['Condition'] == 'Haze' or row['Condition'] == 'Mist':
        weatherData.loc[index, 'Condition'] = 1.5
    elif row['Condition'] == 'Partly Cloudy' or row['Condition'] == 'Light Rain' or row['Condition'] == 'Partly Cloudy / Windy':
        weatherData.loc[index, 'Condition'] = 2
    elif row['Condition'] == 'Thunder in the Vicinity' or row['Condition'] == 'Light Rain with Thunder':
        weatherData.loc[index, 'Condition'] = 2.5
    elif row['Condition'] == 'Mostly Cloudy' or row['Condition'] == 'Mostly Cloudy / Windy':
        weatherData.loc[index, 'Condition'] = 3
    elif row['Condition'] == 'Thunder':
        weatherData.loc[index, 'Condition'] = 3.5
    elif row['Condition'] == 'Cloudy' or row['Condition'] == 'T-Storm' or row['Condition'] == 'Cloudy / Windy':
        weatherData.loc[index, 'Condition'] = 4
    else:
        weatherData.loc[index, 'Condition'] = 4.5
        
for index, row in weatherData.iterrows():
    if row['Wind Dir'] == 'N' or row['Wind Dir'] == 'S':
        weatherData.loc[index, 'Wind Dir'] = 1
    elif row['Wind Dir'] == 'E' or row['Wind Dir'] == 'W':
        weatherData.loc[index, 'Wind Dir'] = 2
    elif row['Wind Dir'] == 'ENE' or row['Wind Dir'] == 'VAR' or row['Wind Dir'] == 'WSW' or row['Wind Dir'] == 'WNW' or row['Wind Dir'] == 'ESE':
        weatherData.loc[index, 'Wind Dir'] = 2.5
    elif row['Wind Dir'] == 'SSW' or row['Wind Dir'] == 'SSE' or row['Wind Dir'] == 'NNW' or row['Wind Dir'] == 'NNE':
        weatherData.loc[index, 'Wind Dir'] = 3
    elif row['Wind Dir'] == 'NE' or row['Wind Dir'] == 'SW' or row['Wind Dir'] == 'NW' or row['Wind Dir'] == 'SE':
        weatherData.loc[index, 'Wind Dir'] = 3.5
    else:
        weatherData.loc[index, 'Wind Dir'] = 0



display(weatherData)

            Date Time  Outside Temp  Humidity Wind Dir  Wind Speed Condition
6     2019-07-01    6         17.22        88      2.5           3         3
7     2019-07-01    7         20.00        78        3           6         1
8     2019-07-01    8         23.89        69        3           7         1
9     2019-07-01    9         26.11        54      3.5          10         2
10    2019-07-01   10         26.11        54      3.5           9         2
...          ...  ...           ...       ...      ...         ...       ...
2111  2019-08-31   17         20.00        52        2           7         4
2112  2019-08-31   18         18.89        68        2           6         4
2113  2019-08-31   19         17.78        77        2           5         4
2114  2019-08-31   20         17.22        82        2           5         4
2115  2019-08-31   21         17.22        72      2.5          10         1

[985 rows x 7 columns]

In [19]:
#Now the features are prepared to be used in the generation of the Inside Temp feature.

import random
insideTemp = []

for index, row in weatherData.iterrows():
        insideTemp.append(row['Outside Temp'] + (random.randrange(9,11) / ((((12 - int(row['Time'])) ** 2) / 4) + 1)) * (np.sqrt(1/row['Condition'])) + row['Outside Temp'] * (1 - np.sqrt(row['Wind Speed'])) * row['Wind Dir'] / 10 / random.randrange(30, 51))

In [20]:
display(insideTemp)

[17.66632503932685,
 21.03430934709009,
 25.402314642770733,
 27.826178884568925,
 29.21036723926607,
 35.36656286200216,
 37.01179894260486,
 37.4375,
 34.34773780775765,
 33.318317101570265,
 32.12440693537136,
 33.013606655789566,
 31.33849139657116,
 30.55424528301887,
 27.733971629316066,
 27.3307539740094,
 24.017019300191734,
 26.611675581357265,
 28.387619119882107,
 30.782702724211116,
 32.150412762006084,
 32.52319095459361,
 32.793230249351346,
 34.2759720676271,
 25.559295584834743,
 22.302845105058474,
 22.207309593574937,
 22.69028573644653,
 23.866418041186563,
 24.45143048454133,
 26.85528239865198,
 28.917273266690398,
 30.761866666666666,
 31.62241177814487,
 29.465469598368305,
 30.077728016931086,
 29.224400000000003,
 28.703918650810774,
 28.473530237757767,
 27.44651135886479,
 24.238497496426593,
 22.93816977807702,
 21.47021395558604,
 23.924663440432212,
 24.51661860561771,
 27.523221469357026,
 28.567045678629164,
 33.193668231293586,
 34.92991961280768,
 30.726672186068377,
 32.15709955549039,
 34.162200375319316,
 28.419591559603134,
 28.176985071536212,
 28.114739138322815,
 28.192172195347084,
 26.391302674604102,
 24.245531039288718,
 22.862511589437073,
 26.074572490703222,
 29.27108803093666,
 31.60635839965411,
 35.901010463152076,
 38.86990243902439,
 41.89594549371535,
 39.4894979474548,
 36.9413256551575,
 35.074093998970675,
 32.7296025507226,
 32.667249533766245,
 31.675906976744187,
 30.308424889768933,
 27.83468582338308,
 22.925439047591098,
 24.706496580927727,
 26.142453525538222,
 27.31346453874116,
 30.240548611084098,
 30.42148014298424,
 30.431142857142856,
 33.02287762950526,
 29.35236181081147,
 30.160096405932737,
 30.6529988871674,
 28.505642871240127,
 25.49883183437437,
 22.954614680268183,
 22.911469517816887,
 22.474654250768793,
 22.13125245098039,
 21.190576250416182,
 21.336264928511355,
 21.467408867798767,
 22.104178526834527,
 24.087817423565237,
 25.700426352069655,
 27.312231376726352,
 28.886662825559284,
 30.303661764705883,
 28.56180978384411,
 27.40041193758604,
 26.693711608181633,
 25.187544573115314,
 23.852858775534173,
 22.12101667403589,
 21.113767343410903,
 15.937879011023577,
 18.38478515473258,
 20.43471609374637,
 23.67624907014545,
 26.32891187222599,
 29.457580612590228,
 33.54253651355533,
 31.87741935483871,
 29.12285854764505,
 27.58690286936727,
 26.55,
 25.96929194059093,
 25.804077224873264,
 24.4335687496986,
 21.50637209555132,
 20.148740521834704,
 15.707106781186548,
 19.12677068643115,
 22.83539602654991,
 24.95532666087384,
 28.679073828696644,
 32.65909090909091,
 33.631365499043106,
 33.07127462926724,
 30.45795803852345,
 30.21115109692621,
 28.917315198059605,
 28.088068054618343,
 27.912625890268366,
 26.578988743107374,
 24.17523758201061,
 21.38053576941394,
 18.64317641430503,
 22.29532771866729,
 25.60143075037425,
 29.849239048333338,
 32.68430272173605,
 37.314585653306516,
 39.515143983594086,
 33.42540333075851,
 33.01294927088224,
 33.11773509401004,
 33.16711764705882,
 32.93654038091614,
 32.90474137924243,
 31.61502209836674,
 29.36031692677071,
 27.522455490988545,
 24.66802365413404,
 26.109882716993788,
 27.734609931706544,
 30.678079491428576,
 32.127386807044694,
 35.671247672580414,
 37.50986842105263,
 33.60933429119633,
 32.65398248204253,
 29.869609597529003,
 29.166499480984115,
 28.930557784692443,
 28.132879913316415,
 24.93296396663229,
 22.140263686823676,
 21.099310345324973,
 17.493088969357032,
 18.396501526636975,
 20.702342307802294,
 21.35160253456362,
 23.269428559381833,
 25.855392878226894,
 26.929802494915283,
 29.24822924949238,
 26.296793622994343,
 27.849704698706205,
 27.70311708402231,
 27.177617068657344,
 26.66892914291409,
 26.52371532236691,
 23.989382090097553,
 22.288001413260556,
 20.727272727272727,
 23.276135850528696,
 25.544185444606473,
 27.514128728414445,
 31.877791602224235,
 35.53651193861651,
 39.471308583621855,
 39.57495856886281,
 34.71983282954625,
 33.40766120636844,
 31.609089186202333,
 32.94835447082715,
 32.17648756754492,
 31.545307809269843,
 30.26254138468465,
 28.9561115554002,
 20.636456410403056,
 22.4045742224457,
 24.028380717720612,
 25.806732731439784,
 29.871794871794872,
 31.819077682344545,
 34.63952441910836,
 34.84295616412431,
 31.93645833333333,
 30.471089743589744,
 29.284468085106386,
 28.65100854088843,
 27.896013246564106,
 26.502531819503197,
 24.336895253484627,
 22.408451772017308,
 18.601115092465555,
 23.8740587099772,
 26.63350664762583,
 30.155076865486816,
 32.13378947368421,
 33.50880215351701,
 35.97265668285284,
 38.18556,
 36.93949235328847,
 34.43921561493636,
 33.816427297334,
 32.29631343963786,
 30.828085933827598,
 29.16139711316122,
 23.605471000257342,
 24.01297416753597,
 23.15029686469452,
 24.165838676144624,
 27.809368386675928,
 27.333798105593516,
 28.83121580945711,
 30.0034,
 31.28563829787234,
 29.604622155520115,
 29.259135828319568,
 29.108282612100993,
 28.669060301042634,
 25.346425586460484,
 26.246679999999998,
 26.329146993351237,
 22.15703718256951,
 22.393106108485366,
 23.132857787678656,
 23.345471319461737,
 24.823138094560182,
 26.065713172881686,
 29.40662617250397,
 31.432646601178906,
 37.713099693239975,
 35.704800000000006,
 34.5261343047812,
 32.320472706627086,
 29.849931252534404,
 29.352761701549035,
 28.130371695926172,
 27.44656619386941,
 24.08760620915033,
 23.002662223974365,
 19.79,
 23.461379310344828,
 25.40422905823416,
 29.903458789233902,
 31.969018129436026,
 36.49604545454545,
 38.59090909090909,
 38.350517409588925,
 34.52115,
 30.828828290187428,
 27.7652533110588,
 28.52081203201585,
 27.661059616966252,
 27.340641791804245,
 26.236562701594355,
 25.12175102599179,
 26.73857190982239,
 28.22202061463667,
 29.141200366227395,
 30.042614690047404,
 32.42441729004666,
 36.05588881392012,
 37.10311476058088,
 35.80968638346632,
 34.128140104936556,
 32.5555049199288,
 29.651110960275492,
 26.59506283150183,
 25.57194476144521,
 26.38127653301887,
 26.071668117614745,
 26.20521686084806,
 25.145262145875634,
 25.59895495074103,
 26.65714331433127,
 28.841208298310136,
 29.834053052749173,
 37.52197362873199,
 40.114915451470395,
 39.520409482537914,
 37.5667840582608,
 37.05009460543722,
 36.24091182710682,
 35.54068253536651,
 32.69202560298886,
 24.093943535454446,
 23.892370200874986,
 24.248585353216715,
 22.70101187129037,
 22.79173313732172,
 23.87984132354868,
 25.48881613006358,
 27.81427685880897,
 28.79167233340713,
 30.35683602522959,
 29.761567099455625,
 29.527001761838168,
 28.466763186277838,
 27.388459686944614,
 26.30473909505582,
 26.467573435152982,
 25.071649626483907,
 23.785950980392155,
 23.917204305991916,
 19.053660926497276,
 19.53441244116609,
 21.038898259469743,
 21.454664286052353,
 23.91284244028858,
 27.30507661635188,
 28.037155138782907,
 28.167516439231292,
 27.783171646645997,
 27.629913720383847,
 24.157799842011695,
 24.287394448452787,
 22.655450447292896,
 23.364328616352203,
 22.691050392632423,
 20.39221912524342,
 14.790000000000001,
 18.980425437293142,
 20.555751725292367,
 23.433369182697415,
 26.440663897622432,
 29.559516102816524,
 34.474454265937666,
 33.9787044890535,
 27.72487373415292,
 27.64854820447669,
 25.68208762739847,
 21.50705465057947,
 18.18743615650898,
 18.195219628918746,
 18.032845383015164,
 17.440745976152638,
 16.83486540182822,
 18.2411421335443,
 20.430931314449918,
 22.89603508021579,
 26.807128775930664,
 29.81153379418061,
 33.51559036562698,
 32.09611209518488,
 29.198022970253504,
 28.471692201438255,
 27.571257581758022,
 25.91363401328049,
 25.6763924849097,
 23.31418630544942,
 22.665995513710087,
 19.240174778703196,
 18.719461100657792,
 20.000569745095056,
 24.136583749004203,
 25.30762557649467,
 29.409406891076053,
 33.64799775264074,
 36.102112235033744,
 31.078019583630773,
 29.237911112949657,
 28.39884096737128,
 28.52018910399452,
 27.88147222592708,
 26.100330213767574,
 25.106078945131628,
 22.914368880129402,
 22.554063683751806,
 18.22548653734995,
 22.20641600476138,
 25.698717411641027,
 28.92665102133824,
 31.19736424198292,
 34.42282651153525,
 37.471333333333334,
 34.424977760525465,
 32.25344043947287,
 31.48644833427528,
 30.4866060123962,
 28.844837323924367,
 28.48985349203187,
 27.531387796082722,
 24.168452197761205,
 22.964230167938844,
 22.464050269189624,
 23.065714684380957,
 24.612964280655067,
 28.604257122759503,
 31.599422824966364,
 34.44792348428239,
 36.10427027027027,
 35.378567238240585,
 31.437809783632144,
 29.31853270643097,
 30.763188070810674,
 30.25328183213593,
 29.299080154251165,
 27.831001007483845,
 27.042470159544298,
 26.215048235294116,
 22.428478260869564,
 23.58464901867684,
 26.605111920651,
 27.441557682111387,
 28.248521260130126,
 34.37681487973009,
 38.24444064210719,
 34.46079351596315,
 32.92650380743627,
 31.993540821837243,
 31.943724344299778,
 29.909100341965246,
 28.911299972641356,
 27.697324929836736,
 26.31052775490935,
 25.118832175862746,
 23.360368421052634,
 25.751359102789024,
 27.432847674890983,
 29.43514400580788,
 32.25108859580153,
 36.13545010116425,
 35.32232024417905,
 34.21712298669023,
 36.11190124155624,
 33.14158614569691,
 26.73493202415262,
 24.39351232854077,
 24.07466083026328,
 22.961832030244878,
 22.26599693642844,
 22.338786897643107,
 20.817138743215047,
 22.15838882732787,
 24.56078121104359,
 26.792180859939375,
 30.76158999947111,
 31.511817720684874,
 33.33075172835335,
 33.52189207834102,
 29.725395174227618,
 30.97681229559491,
 29.55145663594023,
 27.749957920118437,
 27.549753313529425,
 26.458854931374844,
 24.055217676409566,
 22.83446150524163,
 19.489381342843487,
 20.749286958872585,
 20.465741454089333,
 21.025641025641026,
 22.901640104791294,
 25.84684794281101,
 27.85862641488312,
 28.08865055333856,
 28.66713712239701,
 28.609533522822144,
 27.416000640063782,
 27.045352180683782,
 24.531335534070177,
 23.209314091274905,
 21.21411443071904,
 20.120364696568597,
 17.032484313211416,
 18.94009748170392,
 21.606858607242113,
 23.783134327377976,
 26.95336,
 30.287433149013644,
 32.721259062957316,
 32.70698283257273,
 30.159636147801272,
 28.8569861888654,
 27.677120818404276,
 27.02314053297857,
 25.722965587159667,
 24.519058836525822,
 22.598185324000415,
 21.089751953649312,
 15.864578186730538,
 19.129728837194463,
 21.713381509943968,
 24.872989462726533,
 27.38818545944267,
 30.52500360451569,
 35.67133391019605,
 32.8804353391859,
 31.647426924697136,
 29.794459679286515,
 28.759550286702453,
 27.963681446988915,
 27.84850090492619,
 25.3816865326217,
 23.086362569258863,
 21.333758823084462,
 15.959123661607919,
 19.15931034482759,
 22.91,
 28.793216730176066,
 31.588482964004804,
 35.17668168916951,
 37.37733174945483,
 35.70808217023297,
 33.315208563644006,
 32.92867222897068,
 29.852567304284168,
 28.154638964193566,
 27.613421525721552,
 26.765258163992236,
 23.987886165134558,
 22.986610467849317,
 19.30584046851524,
 22.9463285421765,
 23.695401294553392,
 26.661124197201598,
 29.246339295012945,
 30.11759501171512,
 32.769515938460366,
 35.59338060644052,
 30.961980515339466,
 30.403484872494882,
 27.038632519922867,
 24.322492318459968,
 23.24260537988621,
 23.056571151685507,
 22.965360359690873,
 22.435881960152674,
 18.596496580927727,
 22.084947981161523,
 24.413238826035812,
 28.828835020823938,
 31.831173544253193,
 35.39246404258402,
 37.57767567567568,
 35.143499746338684,
 32.53329721728895,
 32.460652398406154,
 32.472600198448525,
 32.04491684599279,
 30.570570513003823,
 28.17577589526377,
 26.442458111189694,
 23.12491184904899,
 22.42509198280762,
 23.78998169977973,
 27.703844444444442,
 28.68124856354562,
 28.610725186920646,
 29.875271938165305,
 32.1159504927176,
 30.592133380371582,
 26.93286590562385,
 24.496536662857416,
 23.53207398868025,
 25.269310344827588,
 24.157532744859335,
 23.405451355933646,
 22.63292403586204,
 22.327046961701633,
 20.82695048315003,
 22.38628639450906,
 24.50851678067531,
 26.918199010902562,
 32.04117312708439,
 33.16456855858765,
 30.992825373619887,
 32.8245058886765,
 26.90462934025603,
 28.847137864446715,
 28.63715548972622,
 28.87891777188329,
 27.400241373428404,
 27.457976559571172,
 25.32871038530776,
 21.478919863269255,
 20.75,
 23.336149666005724,
 24.091857142857144,
 26.1897357024715,
 25.08059184486875,
 29.26450256627215,
 32.00771103067893,
 31.45804748990483,
 32.94240174404692,
 29.929517381518924,
 28.593197520992046,
 28.615287186223444,
 27.808407333243338,
 26.473066981132078,
 25.259287925696597,
 23.787264103983798,
 15.870072264915953,
 18.993039844010266,
 25.002015059730695,
 28.378295351796645,
 30.387922751761444,
 31.736999980911126,
 30.169302153517005,
 28.176584462897342,
 28.709301125703565,
 28.653734819347576,
 28.15790493942218,
 26.31687925322798,
 25.18576966266584,
 24.017636550139265,
 22.995271562256114,
 18.13405058018407,
 18.95064092252649,
 21.8,
 24.723436280907748,
 28.62509326512091,
 27.722281532336336,
 32.846324222121886,
 29.698637126275337,
 29.28987058908603,
 27.930720802961936,
 28.182762824660543,
 26.691310101245488,
 24.26618917504877,
 22.986914890895115,
 20.12907488522227,
 19.189428029348253,
 15.942773126251085,
 20.13137931034483,
 21.794165362031148,
 25.627733077281082,
 30.33277053721357,
 33.920769114079654,
 32.48312769189625,
 30.88644528891711,
 29.082781592698794,
 27.225056133056135,
 28.05872340669676,
 28.33219648396572,
 27.679462504223366,
 26.635244533899115,
 24.27850491306012,
 22.56041897055594,
 20.515546870314637,
 22.95912555209048,
 24.540323507797144,
 25.964672332050185,
 30.86642738659631,
 35.056177855676104,
 33.424363874181445,
 35.57342887076272,
 31.645306314961832,
 30.410492145171816,
 28.405672119452202,
 27.416050813403412,
 27.329400181068348,
 25.79560010052383,
 23.6734288455322,
 23.828757680818686,
 22.562445311376894,
 23.422616599686787,
 23.328166535009746,
 23.75713919053316,
 25.795621244657184,
 28.749804551374055,
 36.66008074433055,
 33.686390747268206,
 32.30397973622138,
 31.12685432945748,
 30.02745846785477,
 28.080719133388072,
 27.17789422977831,
 25.772470316400415,
 23.836628635585488,
 22.815970425600273,
 19.25776431336558,
 20.688237090774134,
 23.071342110448555,
 25.21102543238916,
 25.570315604009927,
 27.629993309463178,
 34.543075468313624,
 31.305745624459956,
 31.86970153852613,
 29.763004467705354,
 28.69301556716787,
 28.264894447612907,
 25.227941176470587,
 23.014738720262514,
 22.47928444559032,
 20.993297435828136,
 19.229724677757876,
 20.804618862559977,
 23.564822962443024,
 25.362820318099093,
 29.56362654630863,
 29.46050450699403,
 29.665287154822522,
 26.31490990755854,
 30.550744731494785,
 26.22039959453463,
 24.498757040362808,
 25.191157081036426,
 24.61220930232558,
 22.74342352616538,
 21.916452499784658,
 21.062699285120388,
 19.187250593917327,
 19.408524789656454,
 22.18709174359813,
 22.314323471557962,
 24.72,
 26.341218331636238,
 29.153889578444083,
 28.621044106004863,
 30.758968880682918,
 27.058198082655142,
 27.77596313922657,
 26.94341056034483,
 25.841008995575855,
 24.475633381063314,
 21.52074954172318,
 20.289402017446218,
 20.26246659991682,
 22.16658244770348,
 23.674357681236398,
 26.74849530569345,
 30.829175104546334,
 32.64142545785325,
 36.290930983564934,
 35.69451169077039,
 30.194290362268667,
 32.29525769428388,
 30.16307936556292,
 28.931134535265834,
 27.252950269189625,
 26.146618877435323,
 24.864479554276862,
 24.105827330109214,
 21.91341504657638,
 23.57443514116291,
 25.265322405456523,
 28.806152243589743,
 32.033360248110185,
 35.94802681454031,
 37.71312244897959,
 27.887284511439447,
 25.36236309259215,
 26.600959215058747,
 25.923008333039945,
 24.50128861103193,
 24.09800654661849,
 24.46633095814529,
 21.03546344360257,
 19.79301946877618,
 18.404960479635225,
 20.846545749355325,
 23.624114574688406,
 25.47774754990608,
 29.5,
 31.662745427258447,
 31.19504603972791,
 29.530701472819338,
 26.971276352935032,
 27.508725118880154,
 28.811402630240796,
 28.178901788329135,
 26.790285714285712,
 25.393843206511118,
 22.71350687622164,
 21.533529411764704,
 20.687311144297926,
 23.47418596833389,
 25.521403136050004,
 30.01098254062194,
 32.15906260589179,
 34.784372393425976,
 36.63349250390372,
 36.54332,
 34.81981019498597,
 31.86126584275273,
 30.779951542429338,
 28.618711059799665,
 27.37737510649733,
 25.74615267911227,
 22.43574936450225,
 22.29677597340009,
 20.74220408797875,
 20.953175818018227,
 23.492792206135785,
 24.73814185559352,
 27.593734178520855,
 31.2663224129751,
 35.8175629242157,
 35.350942332860875,
 28.95405503104577,
 30.96271348723901,
 31.51086956521739,
 29.141214662229967,
 28.040003426670545,
 26.165259221190276,
 26.23203447207233,
 24.95461606352851,
 19.332861934745207,
 19.490831623082336,
 20.907988184673687,
 21.230769230769234,
 23.733582505470455,
 26.824140827366257,
 28.37235868322132,
 30.537659574468087,
 25.19519711444575,
 26.718734872319747,
 23.537839709873733,
 23.594249569697606,
 21.98843198314252,
 20.114385385241892,
 19.01576546035231,
 17.380812667031183,
 14.622221562272848,
 17.158672325336553,
 19.7108309908979,
 22.6444675448894,
 25.205564798345257,
 28.890138665596506,
 31.146248962016347,
 27.929800138182895,
 26.61915445698838,
 24.786031711038028,
 22.631823529411765,
 21.78174242971247,
 21.617120089821107,
 20.452990252747863,
 18.907561257433393,
 17.972628025227618,
 13.518209986496881,
 16.315528003266675,
 19.224769783374466,
 21.713950905673336,
 24.611759007269267,
 27.828141304347824,
 30.531236125652022,
 28.869759571546556,
 25.46216250988692,
 24.629018019965237,
 23.694498957402203,
 23.200945651935466,
 21.65449121549507,
 19.385527259686658,
 16.555173632492064,
 17.85342668767815,
 15.770072264915953,
 18.312222270468343,
 21.710105692336736,
 23.576805274489153,
 25.834984062874774,
 26.151212767543857,
 28.89084991956782,
 29.595182147666907,
 27.953345366866472,
 25.58537979313738,
 24.303932753232235,
 23.187454280616432,
 21.869759571546556,
 20.5622509680009,
 19.258765307094464,
 17.457083111919097,
 15.773403745302724,
 17.23823695172255,
 20.62554,
 23.32585389420259,
 24.145783064955182,
 30.361591836734696,
 27.23747887418086,
 25.916015133794108,
 24.213991823949403,
 24.101855849501526,
 22.71473255461433,
 19.70347623557534,
 17.847684972471416,
 18.84828069547737,
 17.855187290937135,
 18.695801493985222,
 21.485082195470216,
 21.34295496129486,
 21.62625683191829,
 23.330153944957903,
 25.13404678270832,
 28.56475119374167,
 29.668130648034257,
 28.51041832379037,
 28.207671931132506,
 28.298055051658746,
 28.1437369131249,
 27.96483747760009,
 26.698333866719818,
 24.235915678454017,
 22.560505716606304,
 21.323757147615833,
 16.779875304846396,
 18.875072018791187,
 21.45408135477775,
 24.550629637860997,
 26.54108721873188,
 29.59334594482842,
 29.772599782962764,
 32.57247271633818,
 25.001201951901393,
 26.04709643190766,
 24.521276984221956,
 23.117044012327355,
 23.039489804073348,
 22.26128154190091,
 21.074596072962176,
 19.7783512198514,
 15.893242590562872,
 17.36790833075473,
 20.54119097151536,
 22.47383950827046,
 26.121146304346052,
 30.246417403863223,
 32.40574324324324,
 32.31682064439614,
 29.129235074142677,
 28.60446387774538,
 27.673874446689094,
 26.630240346145655,
 25.5091673086804,
 23.855532154654902,
 22.81716215937609,
 22.489196631857418,
 18.048346043769786,
 19.86858265957832,
 21.743994240501063,
 23.54338986013986,
 26.896367119326282,
 30.893415005893335,
 33.5310525147217,
 31.804461403627737,
 29.698022970253504,
 27.372885917688496,
 26.349525487464923,
 24.97580572379678,
 24.529444141331147,
 22.66254605561624,
 20.34137259745796,
 20.22900661149692,
 14.860093571420201,
 17.34707423684529,
 19.364247549045835,
 21.364969928116228,
 23.1650396644768,
 24.100110215478693,
 25.91327251252774,
 30.012716067796628,
 24.49643538168215,
 22.698817922292864,
 22.071710055362292,
 20.5553081266126,

In [21]:
#Add this feature to the copy of the datafram we made earlier which preserved the non numeric Wind Dir and Condition features

weatherData0['Inside Temp'] = insideTemp
weatherData0['Inside Temp'] = weatherData0['Inside Temp'].round(2)

#Also fix the format of date and time so it can be recognized by tableau as a date/time feature

for index, row in weatherData0.iterrows():
        weatherData0.loc[index, 'Time'] = str(row['Time']) + ':00:00'

display(weatherData0)

,Date,Time,Outside Temp,Humidity,Wind Dir,Wind Speed,Condition,Inside Temp
6,2019-07-01,6:00:00,17.22,88,ENE,3,Mostly Cloudy,17.67
7,2019-07-01,7:00:00,20.00,78,SSE,6,Fair,21.03
8,2019-07-01,8:00:00,23.89,69,SSW,7,Fair,25.40
9,2019-07-01,9:00:00,26.11,54,SW,10,Partly Cloudy,27.83
10,2019-07-01,10:00:00,26.11,54,SW,9,Partly Cloudy,29.21
...,...,...,...,...,...,...,...,...
2111,2019-08-31,17:00:00,20.00,52,E,7,Cloudy,20.56
2112,2019-08-31,18:00:00,18.89,68,E,6,Cloudy,19.17
2113,2019-08-31,19:00:00,17.78,77,E,5,Cloudy,18.03
2114,2019-08-31,20:00:00,17.22,82,E,5,Cloudy,17.42
2115,2019-08-31,21:00:00,17.22,72,ENE,10,Fair,17.44

In [22]:
weatherData0['Date'] = pd.to_datetime(weatherData0.Date, format='%Y-%m-%d')
weatherData0['Date'] = weatherData0['Date'].dt.strftime('%m/%d/%Y')
display(weatherData0)

,Date,Time,Outside Temp,Humidity,Wind Dir,Wind Speed,Condition,Inside Temp
6,07/01/2019,6:00:00,17.22,88,ENE,3,Mostly Cloudy,17.67
7,07/01/2019,7:00:00,20.00,78,SSE,6,Fair,21.03
8,07/01/2019,8:00:00,23.89,69,SSW,7,Fair,25.40
9,07/01/2019,9:00:00,26.11,54,SW,10,Partly Cloudy,27.83
10,07/01/2019,10:00:00,26.11,54,SW,9,Partly Cloudy,29.21
...,...,...,...,...,...,...,...,...
2111,08/31/2019,17:00:00,20.00,52,E,7,Cloudy,20.56
2112,08/31/2019,18:00:00,18.89,68,E,6,Cloudy,19.17
2113,08/31/2019,19:00:00,17.78,77,E,5,Cloudy,18.03
2114,08/31/2019,20:00:00,17.22,82,E,5,Cloudy,17.42
2115,08/31/2019,21:00:00,17.22,72,ENE,10,Fair,17.44

In [23]:
#Shift the Inside temp values so each row has a reference of the inside temp 1 hour earlier (This is we removed the rows 
#earlier that weren't on the hour)

prevTemps = weatherData0['Inside Temp']
prevTemps = prevTemps[:-1]
addTemps = [16]
addTemps[1:] = prevTemps
weatherData0['Inside Temp 1Hr Ago'] = addTemps
display(weatherData0)

,Date,Time,Outside Temp,Humidity,Wind Dir,Wind Speed,Condition,Inside Temp,Inside Temp 1Hr Ago
6,07/01/2019,6:00:00,17.22,88,ENE,3,Mostly Cloudy,17.67,16.00
7,07/01/2019,7:00:00,20.00,78,SSE,6,Fair,21.03,17.67
8,07/01/2019,8:00:00,23.89,69,SSW,7,Fair,25.40,21.03
9,07/01/2019,9:00:00,26.11,54,SW,10,Partly Cloudy,27.83,25.40
10,07/01/2019,10:00:00,26.11,54,SW,9,Partly Cloudy,29.21,27.83
...,...,...,...,...,...,...,...,...,...
2111,08/31/2019,17:00:00,20.00,52,E,7,Cloudy,20.56,22.07
2112,08/31/2019,18:00:00,18.89,68,E,6,Cloudy,19.17,20.56
2113,08/31/2019,19:00:00,17.78,77,E,5,Cloudy,18.03,19.17
2114,08/31/2019,20:00:00,17.22,82,E,5,Cloudy,17.42,18.03
2115,08/31/2019,21:00:00,17.22,72,ENE,10,Fair,17.44,17.42

In [24]:
#Data is preped, output the dataframe to be used with tableau to gather insights.

weatherData0.to_csv(r'C:\Users\Gavo_\Documents\AIDI_1002\WeatherOut.csv', index = False)

In [25]:
display(weatherData)

            Date Time  Outside Temp  Humidity Wind Dir  Wind Speed Condition
6     2019-07-01    6         17.22        88      2.5           3         3
7     2019-07-01    7         20.00        78        3           6         1
8     2019-07-01    8         23.89        69        3           7         1
9     2019-07-01    9         26.11        54      3.5          10         2
10    2019-07-01   10         26.11        54      3.5           9         2
...          ...  ...           ...       ...      ...         ...       ...
2111  2019-08-31   17         20.00        52        2           7         4
2112  2019-08-31   18         18.89        68        2           6         4
2113  2019-08-31   19         17.78        77        2           5         4
2114  2019-08-31   20         17.22        82        2           5         4
2115  2019-08-31   21         17.22        72      2.5          10         1

[985 rows x 7 columns]

In [26]:
weatherDataMod1 = weatherData.copy()
weatherDataMod2 = weatherData.copy()

In [27]:
weatherDataMod1['Inside Temp'] = weatherData0['Inside Temp']
weatherDataMod2['Inside Temp'] = weatherData0['Inside Temp']
weatherDataMod2['Inside Temp 1Hr Ago'] = weatherData0['Inside Temp 1Hr Ago']

In [28]:
weatherDataMod1 = weatherDataMod1.drop(['Date'], axis = 1)
weatherDataMod2 = weatherDataMod2.drop(['Date'], axis = 1)

display(weatherDataMod1)
display(weatherDataMod2)

     Time  Outside Temp  Humidity Wind Dir  Wind Speed Condition  Inside Temp
6       6         17.22        88      2.5           3         3        17.67
7       7         20.00        78        3           6         1        21.03
8       8         23.89        69        3           7         1        25.40
9       9         26.11        54      3.5          10         2        27.83
10     10         26.11        54      3.5           9         2        29.21
...   ...           ...       ...      ...         ...       ...          ...
2111   17         20.00        52        2           7         4        20.56
2112   18         18.89        68        2           6         4        19.17
2113   19         17.78        77        2           5         4        18.03
2114   20         17.22        82        2           5         4        17.42
2115   21         17.22        72      2.5          10         1        17.44

[985 rows x 7 columns]

,Time,Outside Temp,Humidity,Wind Dir,Wind Speed,Condition,Inside Temp,Inside Temp 1Hr Ago
6,6,17.22,88,2.5,3,3,17.67,16.00
7,7,20.00,78,3,6,1,21.03,17.67
8,8,23.89,69,3,7,1,25.40,21.03
9,9,26.11,54,3.5,10,2,27.83,25.40
10,10,26.11,54,3.5,9,2,29.21,27.83
...,...,...,...,...,...,...,...,...
2111,17,20.00,52,2,7,4,20.56,22.07
2112,18,18.89,68,2,6,4,19.17,20.56
2113,19,17.78,77,2,5,4,18.03,19.17
2114,20,17.22,82,2,5,4,17.42,18.03
2115,21,17.22,72,2.5,10,1,17.44,17.42

In [29]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split

In [48]:
X = weatherDataMod1.drop(['Inside Temp', 'Humidity'], axis = 1)
y = weatherDataMod1['Inside Temp']

In [49]:
(X_train, X_test, y_train, y_test) = train_test_split(X, y, test_size=0.3, random_state=0)

In [50]:
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(X_train)

In [51]:
model = LinearRegression()
model.fit(x_poly, y_train)
y_poly_pred = model.predict(x_poly)

rmse = np.sqrt(mean_squared_error(y_train, y_poly_pred))
r2 = r2_score(y_train, y_poly_pred)

from sklearn.metrics import mean_absolute_error
print('Mean Absolute Error:',mean_absolute_error(y_train, y_poly_pred))
print('Root Mean Squared Error:', rmse)
print('R-squared (R2):', r2)

Mean Absolute Error: 1.158336100505439
Root Mean Squared Error: 1.4594684287029045
R-squared (R2): 0.9156458947351662

In [63]:
testVal = polynomial_features.fit_transform([[12, 20, 2, 7, 1]])

model.predict(testVal)

array([24.46482663])

In [64]:
import pickle

In [65]:
pickle.dump(model, open('model.pkl', 'wb'))

In [66]:
testModel = pickle.load(open('model.pkl', 'rb'))
print(testModel.predict(testVal))

[24.46482663]